config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: "pages#home"
  # root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  reject_if: lambda { |attrs| attrs["name"].blank? }

    include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image

    def self.angular # Class method
        where(subtitle: "Angular")
    end

    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') } # lambda function

    after_initialize :set_defaults # after_initialize do when new method in controller run at the same time(callback)

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
        self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
    end

    # meaning of self.main_image ||= "https://placehold.co/600x400"
    # if self.main_image == nil
    #   self.main_image == "https://placehold.co/600x400"
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    layout "portfolio"
    
    def index
        @portfolio_items = Portfolio.all
        # @portfolio_items = Portfolio.where(subtitle: "Angular")
    end

    def angular
        @portfolio_angular_items = Portfolio.angular
    end

    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)

        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_url, notice: "Blog was successfully created." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @portfolio_item = Portfolio.find(params[:id])
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])

        respond_to do |format|
            if @portfolio_item.update(portfolio_params)
                format.html { redirect_to portfolios_url, notice: "The record successfully updated." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def show
        @portfolio_item = Portfolio.find(params[:id])
    end

    def destroy
        @portfolio_item = Portfolio.find(params[:id])

        @portfolio_item.destroy

        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: "Portfolio was successfully destroyed." }
          end
    end

    private
        def portfolio_params
            params.require(:portfolio).permit(:title, 
                                              :subtitle,
                                              :body, 
                                              technologies_attributes: [:name])
        end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    
<p><%= portfolio_item.subtitle %></p>

<p><%= portfolio_item.body %></p>

<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>

<%= link_to"Edit", edit_portfolio_path(portfolio_item) %>

<%= button_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, onclick: "return confirm('Are you sure?');" %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolio_angular_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to"Edit", edit_portfolio_path(portfolio_item) %>
    <%= button_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, onclick: "return confirm('Are you sure?');" %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_for(@portfolio_item) do |form| %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<div>
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

 <%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

<div>
  <%= link_to "Back to portfolios", portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle%></em>

<p><%= @portfolio_item.body%></p>

<h2>Technoloy Used:</h2>

<% @portfolio_item.technologies.each do |t| %>
    <p><%= t.name %></p>
<% end %>

<hr>

<%= session.inspect %>
<%# <hr>
<%= params.inspect  <br>
<%= Portfolio.find(params[:id]).title %>